---
- hosts: myhost
  tasks:
  - name: Read users from CSV file and return a dictionary
    read_csv:
      path: users.csv
      key: name
    register: users
  - debug:
      msg: '{{ users }}'
  - debug:
      msg: 'User {{ users.dict.bob.name }} has UID {{ users.dict.bob.uid }} and GID {{ users.dict.bob.gid }}'

# bob:
#     name:
#     uid:
#     gid:
# alice:
#     name:
#     uid:
#     gid:

# portno service named
# 80    https
# 22    ssh

# register : xyz
#  80:
#    portno:
#   seciename:

# firewalld:
#         service: "{{ xyz.dict.80.port.service name }}"
#         permanent: true
#         immediate: true
#         state: enabled
#         portno:{{ xyz.dict.80.portno }}


